// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lPUwrT6K13OPykGUP38dAzKz9JBXTQk',
    appId: '1:248315500994:web:c15c9d5ca85263fa5ade5b',
    messagingSenderId: '248315500994',
    projectId: 'tobahack-de5bb',
    authDomain: 'tobahack-de5bb.firebaseapp.com',
    storageBucket: 'tobahack-de5bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3NtH1MqAmWKMXc79U-sVjM-0x3JeCjg',
    appId: '1:248315500994:android:ef7c58339d4719895ade5b',
    messagingSenderId: '248315500994',
    projectId: 'tobahack-de5bb',
    storageBucket: 'tobahack-de5bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7joqWPotWwNF_oGNh4VOCQkSigdpJjhA',
    appId: '1:248315500994:ios:854a6c0107f2731e5ade5b',
    messagingSenderId: '248315500994',
    projectId: 'tobahack-de5bb',
    storageBucket: 'tobahack-de5bb.appspot.com',
    iosBundleId: 'com.example.tobas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7joqWPotWwNF_oGNh4VOCQkSigdpJjhA',
    appId: '1:248315500994:ios:a4dc818e8b7d77f35ade5b',
    messagingSenderId: '248315500994',
    projectId: 'tobahack-de5bb',
    storageBucket: 'tobahack-de5bb.appspot.com',
    iosBundleId: 'com.example.tobas.RunnerTests',
  );
}
